FROM python:3.8-slim-buster

WORKDIR /python-docker

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY D2_flask.py .
EXPOSE 5000
CMD [ "python3", "-m" , "flask","--app","D2_flask.py", "run", "--host=0.0.0.0"]